version: '3.8'

services:
  k8s-reflexion-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GO_SERVICE_URL=http://k8s-ai-agent:8080
      - REFLECTION_DEPTH=medium
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
      - ./reflexion_memory.json:/app/reflexion_memory.json
    networks:
      - k8s-ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Mock Go service for development (optional)
  mock-go-service:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./mock-responses:/usr/share/nginx/html
    networks:
      - k8s-ai-network
    profiles:
      - mock

networks:
  k8s-ai-network:
    driver: bridge

volumes:
  reflexion-logs:
  reflexion-data: