# Comprehensive Kubernetes Error Test Scenarios
# Her senaryo farklı hata türünü test eder

---
# 1. ImagePullBackOff - Geçersiz image tag
apiVersion: v1
kind: Pod
metadata:
  name: test-imagepull-error
  labels:
    test-category: image-errors
spec:
  containers:
  - name: broken-image
    image: nginx:nonexistent-tag-12345
  restartPolicy: Never

---
# 2. InvalidImageName - Hatalı image format
apiVersion: v1
kind: Pod
metadata:
  name: test-invalid-name
  labels:
    test-category: image-errors
spec:
  containers:
  - name: invalid-format
    image: "INVALID/IMAGE/NAME@#$%"
  restartPolicy: Never

---
# 3. ErrImagePull - Private registry access
apiVersion: v1
kind: Pod
metadata:
  name: test-private-image
  labels:
    test-category: image-errors
spec:
  containers:
  - name: private-repo
    image: private.registry.com/secret/app:latest
  restartPolicy: Never

---
# 4. CrashLoopBackOff - Exit code 1
apiVersion: v1
kind: Pod
metadata:
  name: test-crash-exit1
  labels:
    test-category: crash-errors
spec:
  containers:
  - name: crash-app
    image: busybox
    command: ["sh", "-c", "echo 'Starting...'; sleep 2; echo 'Crashing!'; exit 1"]
  restartPolicy: Always

---
# 5. CrashLoopBackOff - Exit code 2
apiVersion: v1
kind: Pod
metadata:
  name: test-crash-exit2
  labels:
    test-category: crash-errors
spec:
  containers:
  - name: crash-app-2
    image: busybox
    command: ["sh", "-c", "echo 'Configuration error'; exit 2"]
  restartPolicy: Always

---
# 6. OOMKilled - Memory limit exceeded
apiVersion: v1
kind: Pod
metadata:
  name: test-oom-memory
  labels:
    test-category: resource-errors
spec:
  containers:
  - name: memory-hog
    image: polinux/stress
    resources:
      limits:
        memory: "20Mi"
      requests:
        memory: "10Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "50M", "--timeout", "30s"]
  restartPolicy: Never

---
# 7. CreateContainerConfigError - Wrong volume mount
apiVersion: v1
kind: Pod
metadata:
  name: test-config-error
  labels:
    test-category: config-errors
spec:
  containers:
  - name: config-app
    image: nginx
    volumeMounts:
    - name: nonexistent-volume
      mountPath: /app/config
  # volumes: section missing - creates error
  restartPolicy: Never

---
# 8. CreateContainerError - Invalid command
apiVersion: v1
kind: Pod
metadata:
  name: test-container-error
  labels:
    test-category: config-errors
spec:
  containers:
  - name: invalid-cmd
    image: nginx
    command: ["/nonexistent/binary"]
    args: ["--invalid-flag"]
  restartPolicy: Never

---
# 9. PodPending - Insufficient resources
apiVersion: v1
kind: Pod
metadata:
  name: test-pending-resources
  labels:
    test-category: scheduling-errors
spec:
  containers:
  - name: resource-hungry
    image: nginx
    resources:
      requests:
        memory: "100Gi"  # Unrealistic memory request
        cpu: "50"        # 50 CPU cores
      limits:
        memory: "100Gi"
        cpu: "50"
  restartPolicy: Never

---
# 10. PodPending - Node selector mismatch
apiVersion: v1
kind: Pod
metadata:
  name: test-pending-selector
  labels:
    test-category: scheduling-errors
spec:
  nodeSelector:
    nonexistent-label: "true"
  containers:
  - name: selector-app
    image: nginx
  restartPolicy: Never

---
# 11. Init Container Failure
apiVersion: v1
kind: Pod
metadata:
  name: test-init-failure
  labels:
    test-category: init-errors
spec:
  initContainers:
  - name: failing-init
    image: busybox
    command: ["sh", "-c", "echo 'Init failing...'; exit 1"]
  containers:
  - name: main-app
    image: nginx
  restartPolicy: Never

---
# 12. Multi-container failure
apiVersion: v1
kind: Pod
metadata:
  name: test-multi-container
  labels:
    test-category: complex-errors
spec:
  containers:
  - name: container-1
    image: nginx:invalid-tag
  - name: container-2
    image: busybox
    command: ["sleep", "300"]
  restartPolicy: Never

---
# 13. Segmentation Fault (Exit 139)
apiVersion: v1
kind: Pod
metadata:
  name: test-segfault
  labels:
    test-category: crash-errors
spec:
  containers:
  - name: segfault-app
    image: busybox
    command: ["sh", "-c", "echo 'Causing segfault...'; kill -11 $$"]
  restartPolicy: Never

---
# 14. SIGTERM (Exit 143)
apiVersion: v1
kind: Pod
metadata:
  name: test-sigterm
  labels:
    test-category: signal-errors
spec:
  containers:
  - name: sigterm-app
    image: busybox
    command: ["sh", "-c", "echo 'Sending SIGTERM...'; kill -15 $$"]
  restartPolicy: Never

---
# 15. Resource conflict - Request > Limit
apiVersion: v1
kind: Pod
metadata:
  name: test-resource-conflict
  labels:
    test-category: validation-errors
spec:
  containers:
  - name: conflict-app
    image: nginx
    resources:
      requests:
        memory: "1Gi"
        cpu: "2"
      limits:
        memory: "500Mi"  # Request > Limit
        cpu: "1"         # Request > Limit
  restartPolicy: Never