apiVersion: v1
kind: Pod
metadata:
  name: crashloop-test-lessons
  labels:
    test: crashloop-lessons
spec:
  containers:
  - name: crash-container
    image: busybox
    command: ["sh", "-c"]
    args: ["echo 'Starting...'; sleep 2; echo 'Crashing now!'; exit 1"]
  restartPolicy: Always