apiVersion: v1
kind: Pod
metadata:
  name: test-cannotrun-pod
  namespace: default
  labels:
    app: cannotrun-test
spec:
  containers:
  - name: cannotrun-container
    image: busybox:latest
    command: ["/nonexistent/binary"]
    args: ["--invalid-arg"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
  restartPolicy: Always