apiVersion: v1
kind: Pod
metadata:
  name: memory-stress-test
  namespace: default
  labels:
    test-type: memory-limit
    scenario: oom-killer
spec:
  containers:
  - name: memory-eater
    image: polinux/stress
    resources:
      limits:
        memory: "50Mi"
        cpu: "0.1"
      requests:
        memory: "10Mi"
        cpu: "0.05"
    command: ["stress"]
    args: 
    - "--vm"
    - "1"
    - "--vm-bytes"
    - "100M"
    - "--timeout"
    - "120s"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: memory-gradual-test
  namespace: default
  labels:
    test-type: memory-gradual
    scenario: slow-memory-leak
spec:
  containers:
  - name: memory-leak
    image: busybox
    resources:
      limits:
        memory: "30Mi"
        cpu: "0.1"
      requests:
        memory: "5Mi"
        cpu: "0.05"
    command: ["sh"]
    args:
    - "-c"
    - |
      echo "Starting memory test..."
      # Gradual memory consumption
      i=0
      while [ $i -lt 1000 ]; do
        # Create large variable to consume memory
        large_var=$(yes | head -c 1M)
        echo "Memory iteration: $i"
        sleep 1
        i=$((i+1))
      done
  restartPolicy: Never