apiVersion: v1
kind: Pod
metadata:
  name: yaml-test-oom
  labels:
    test: yaml-mode
spec:
  containers:
  - name: memory-hog
    image: polinux/stress
    resources:
      limits:
        memory: "10Mi"
        cpu: "100m"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "50M", "--vm-hang", "1"]
  restartPolicy: Never