apiVersion: v1
kind: Pod
metadata:
  name: test-imagepull-pod
  namespace: default
  labels:
    app: imagepull-test
spec:
  containers:
  - name: imagepull-container
    image: nonexistent-registry.com/fake-image:v1.0.0
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
  restartPolicy: Always